### ISSUE TITLE
_config.h

### ISSUE THREAD

**Issue by paulwratt** [solcloud/NiceOS#1]
line 31: `export MAKEFLAGS="-j${MAKE_NUM_OF_THREATS}"`

shouldn't that be "THREADS"

also I think there is a better way to do that (now if I could just find it - a couple of weeks ago I saw something, and its available on RPiOS, so Debian)

its equivalent to: `cat /proc/cpuinfo | grep "^processor" | wc -l`

yeah, found it: `export MAKEFLAGS="-j$(nproc)"`

on that note, I prefer to have my gui responsive, so I always use `nproc - 1`, if you dont care about GUI response (even on console) then `nproc + 1` is optimal (they are threads anyway)

EDIT: or maybe I should just read the top of the file before posting "issue" ...

**Comment by solcloud** [comment]
Well hello SerenityOS friend,
yop probably threads is better word :) Good catch, you spot that on video or you were just poking around of source code?

for defaults values... currently not many people using NiceOS (only me) so _config is basically my config and I just forcing people to edit it to suit their needs, mostly changing base params should be enough tho
`$EDITOR _config.sh # read carefully and make modifications`
but if this project became more famous I will probably add ignored config.sh that main _config file will source so people can keep their local config untouched
