### ISSUE TITLE
Using custom (non vanilla) kernel like Nobara

### ISSUE THREAD

**Issue by godalming123** [solcloud/NiceOS#10]
Is it possible to add nobar linux ( https://nobaraproject.org ) to the supported distris it's like fedora but with a kernel customized for performance

**Comment by solcloud** [comment]
I don't have experience with Nobara, but if they only provide some kernel patches you can download their kernel source and then use it inside NiceOS instead of vanilla one using `NICE_LINUX_ARCHIVE_PATH` environment variable, eg:

```bash
NICE_LINUX_ARCHIVE_PATH=/path/to/nobara.kernel.tar.xz make linux
```
and extract packages from fedora

**Comment by solcloud** [comment]
Feel free to reopen if issue still persist
