### ISSUE TITLE
Unclarity in the README

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [solcloud/NiceOS#9]
> You can do it, try it and make NiceOS your last Linux distribution ever!

Do _what_, please? Try the OS? But that is what the sentence _proceeds_ to say . . . I would suggest a correction, were it not that I do not know the intended meaning.

Good luck with your project!

EDITED because, er, I forgot to mark the first sentence as a quotation. Indeed, let me now add the following. Now that I come to look at the sentence again (the quoted sentence), I . . er . . understand it!

**Comment by solcloud** [comment]
ok sure, done ;)

**Comment by ghost** [comment]
@solcloud I still don't fully understand what this distribution is. Could you please be more specific? For example:

> Void Linux is an independent Linux distribution that uses the X Binary Package System (XBPS) package manager, which was designed and implemented from scratch, and the runit init system.

The current description confuses new users C:

**Comment by solcloud** [comment]
@nvidiaLinuxUser It is indeed every Linux distro replacement. NiceOS is **fully** customizable Linux distribution, so can use for whatever you want. I mean you can literally create "another" distibutions using NiceOS. You can easily create void preset that mimic official void install cd and called my-void distro, arch preset that mimic official one, ubuntu preset that mimic official one, whatever - every distro replacement.

I agree that I am  not really good at explaining what this is and how to attract new users, but at the end, it works for me, and I tried record many tutorials on youtube and whole source code for NiceOS (scripts/ folder) is less than 600 lines so you can audit it in one hour. 

But maybe quote it something like:

> NiceOS is Linux distribution for advance users, that uses whatever package manager you like the most. It was designed to fulfill goal of easily building disk images for different target machines with fewest user interaction as possible and to stop pollution of distros that just use some major distro as base. At the end Linux is just kernel and everything is file and distribution is just package manager that manages those files. NiceOS by default provide minimal sets of files (target/ folder) to build general purpose system and it is user job to extend or replace this defaults to fulfill her goal using presets concept. After user creates his preset, user is than free to distribute this preset (called distro, my distro...) to whatever end machines or users she wants.

**Comment by solcloud** [comment]
Also feel free to send pull request for Readme.md if you have ideas how to enhance it.
